// Code generated by "stringer -type=Button"; DO NOT EDIT.

package lcm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Up-1]
	_ = x[Down-2]
	_ = x[Back-3]
	_ = x[Enter-4]
}

const _Button_name = "UpDownBackEnter"

var _Button_index = [...]uint8{0, 2, 6, 10, 15}

func (i Button) String() string {
	i -= 1
	if i >= Button(len(_Button_index)-1) {
		return "Button(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Button_name[_Button_index[i]:_Button_index[i+1]]
}
